version: '3'
services:

    mysql:
        image: mysql:latest
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: fyc_mysql
        volumes:
            - .docker/database/data:/var/lib/mysql
        env_file:
            - .docker/database/secrets.env
        expose:
            - 3306
        ports: 
            - 3306:3306
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: fyc_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql
        restart: always
